{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# ⚡ 🇹🇭 เตรียมชุดข้อมูลเสียงภาษาไทย (Porjai Central) [Speedrun Edition]\n",
        "\n",
        "ดาวน์โหลดชุดข้อมูล **CMKL/Porjai-Thai-voice-dataset-central** (335,674 ตัวอย่าง!)\n",
        "ผ่าน **Parquet API** ที่เร็วที่สุด แล้วแปลงเป็น WAV + JSONL สำหรับ Notebook 2\n",
        "\n",
        "**เทคนิค:**\n",
        "1. `Parquet API`: ดาวน์โหลด dataset ทั้งหมดผ่าน Parquet files\n",
        "2. `Byte-size Pre-filter`: ข้ามไฟล์สั้น/ยาวเกินก่อนแปลง\n",
        "3. `Chunk-by-chunk Processing`: ประมวลผลทีละ Parquet file → ปล่อย RAM ทันที\n",
        "4. `Parallel FFmpeg`: แปลง MP3→WAV ด้วย multi-process\n",
        "5. `Accurate Duration`: คำนวณ duration จริงจาก WAV (double-check)\n",
        "\n",
        "**โครงสร้างโฟลเดอร์:**\n",
        "- `prep/` — ข้อมูลดิบชั่วคราว (Parquet, WAV, JSONL) จะถูกลบเมื่อเสร็จ\n",
        "- `dataset/` — เฉพาะ vectorized output ที่ Notebook 2 ต้องการเท่านั้น"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ติดตั้ง dependencies\n",
        "!apt-get update -qq && apt-get install -y -qq aria2\n",
        "!pip install pandas pyarrow requests psutil tqdm -q"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### ⚙️ ส่วนที่ 1: ตั้งค่าระบบ (Configuration)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "import json\n",
        "import os\n",
        "import gc\n",
        "import subprocess\n",
        "import sys\n",
        "import concurrent.futures\n",
        "import multiprocessing\n",
        "import psutil\n",
        "import pandas as pd\n",
        "import requests\n",
        "from tqdm import tqdm\n",
        "\n",
        "os.environ[\"TOKENIZERS_PARALLELISM\"] = \"false\"\n",
        "\n",
        "KAGGLE_WORKING = \"/kaggle/working\"\n",
        "PREP_DIR       = os.path.join(KAGGLE_WORKING, \"prep\")\n",
        "PARQUET_DIR    = os.path.join(PREP_DIR, \"parquet\")\n",
        "OUTPUT_WAV_DIR = os.path.join(PREP_DIR, \"th_wavs\")\n",
        "OUTPUT_JSONL   = os.path.join(PREP_DIR, \"train.jsonl\")\n",
        "\n",
        "TARGET_SAMPLE_RATE = 24000\n",
        "TARGET_CHANNELS    = 1\n",
        "\n",
        "# === กรอง Duration (วินาที) ===\n",
        "MIN_DURATION_SEC = 0.5\n",
        "MAX_DURATION_SEC = 30.0\n",
        "\n",
        "# === จำนวนตัวอย่างที่ต้องการ ===\n",
        "# ตั้งเป็น None เพื่อใช้ทั้งหมด, หรือตั้งเป็นตัวเลข\n",
        "MAX_CLIPS = 50000\n",
        "\n",
        "# URL ของ Parquet files\n",
        "PARQUET_BASE_URL = \"https://huggingface.co/api/datasets/CMKL/Porjai-Thai-voice-dataset-central/parquet/default/train\"\n",
        "\n",
        "print(f\"📋 Config: MAX_CLIPS={MAX_CLIPS}, SR={TARGET_SAMPLE_RATE}Hz\")\n",
        "print(f\"📋 Duration filter: {MIN_DURATION_SEC}s - {MAX_DURATION_SEC}s\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 📥 ส่วนที่ 2: ดาวน์โหลด Parquet Files ด้วย Aria2"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "os.makedirs(PARQUET_DIR, exist_ok=True)\n",
        "\n",
        "print(\"🔍 กำลังดึงรายการ Parquet files...\")\n",
        "response = requests.get(PARQUET_BASE_URL)\n",
        "response.raise_for_status()\n",
        "parquet_urls = response.json()\n",
        "print(f\"📦 พบ {len(parquet_urls)} Parquet files\")\n",
        "\n",
        "for i, url in enumerate(parquet_urls):\n",
        "    filename = f\"{i}.parquet\"\n",
        "    filepath = os.path.join(PARQUET_DIR, filename)\n",
        "    if not os.path.exists(filepath):\n",
        "        print(f\"⬇️  Downloading {filename} ({i+1}/{len(parquet_urls)})...\")\n",
        "        subprocess.run([\n",
        "            \"aria2c\", \"-x\", \"16\", \"-s\", \"16\", \"-k\", \"1M\",\n",
        "            \"--console-log-level=error\",\n",
        "            \"-o\", filename, \"-d\", PARQUET_DIR, url\n",
        "        ], check=True)\n",
        "    else:\n",
        "        print(f\"✅ {filename} already exists\")\n",
        "\n",
        "print(f\"\\n✅ ดาวน์โหลด Parquet files ทั้ง {len(parquet_urls)} ไฟล์เสร็จสิ้น!\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### ⚡ ส่วนที่ 3: อ่าน Parquet → Pre-filter → แปลง WAV **ทีละ chunk**\n",
        "\n",
        "**ประมวลผลทีละ Parquet file** เพื่อป้องกัน RAM/Disk เต็ม:\n",
        "1. โหลด 1 Parquet file เข้า RAM\n",
        "2. Pre-filter ด้วย byte-size\n",
        "3. แปลง MP3→WAV แบบ parallel\n",
        "4. **ปล่อย RAM ของ MP3 bytes ทันที** (del + gc.collect)\n",
        "5. ไป Parquet file ถัดไป\n",
        "\n",
        "WAV ที่ไม่ผ่าน duration check → **ลบจาก disk ทันที**"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "import pyarrow.parquet as pq\n",
        "\n",
        "os.makedirs(OUTPUT_WAV_DIR, exist_ok=True)\n",
        "\n",
        "# === Pre-filter ===\n",
        "MP3_MIN_BITRATE = 64_000\n",
        "MP3_MAX_BITRATE = 320_000\n",
        "\n",
        "def pre_filter_by_size(audio_bytes, min_sec, max_sec):\n",
        "    size_bits = len(audio_bytes) * 8\n",
        "    if size_bits / MP3_MIN_BITRATE < min_sec:\n",
        "        return 'short'\n",
        "    if size_bits / MP3_MAX_BITRATE > max_sec:\n",
        "        return 'long'\n",
        "    return 'ok'\n",
        "\n",
        "# === Worker function ===\n",
        "def process_audio_item(args):\n",
        "    \"\"\"แปลง MP3 bytes → WAV แล้วคำนวณ duration จริง\n",
        "    WAV ที่ไม่ผ่านเกณฑ์จะถูกลบจาก disk ทันที\"\"\"\n",
        "    audio_bytes, sentence, base_name, wav_dir, sr, ch, min_dur, max_dur = args\n",
        "    \n",
        "    wav_filename = f\"{base_name}.wav\"\n",
        "    wav_path = os.path.join(wav_dir, wav_filename)\n",
        "    \n",
        "    process = subprocess.Popen([\n",
        "        \"ffmpeg\", \"-y\", \"-i\", \"pipe:0\",\n",
        "        \"-ar\", str(sr), \"-ac\", str(ch),\n",
        "        \"-sample_fmt\", \"s16\", \"-threads\", \"1\",\n",
        "        wav_path\n",
        "    ], stdin=subprocess.PIPE, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)\n",
        "    process.communicate(input=audio_bytes)\n",
        "    \n",
        "    if process.returncode != 0 or not os.path.exists(wav_path):\n",
        "        return None\n",
        "    \n",
        "    # คำนวณ duration จริงจาก WAV\n",
        "    try:\n",
        "        file_size = os.path.getsize(wav_path)\n",
        "        duration = (file_size - 44) / 2 / sr\n",
        "    except Exception:\n",
        "        duration = 0.0\n",
        "    \n",
        "    # ไม่ผ่าน → ลบ WAV ทันที!\n",
        "    if duration < min_dur or duration > max_dur:\n",
        "        os.remove(wav_path)\n",
        "        return None\n",
        "    \n",
        "    return json.dumps({\n",
        "        \"transcript\": sentence,\n",
        "        \"language\": \"th\",\n",
        "        \"wav_path\": wav_path,\n",
        "        \"duration\": round(duration, 3),\n",
        "        \"sample_rate\": sr\n",
        "    }, ensure_ascii=False)\n",
        "\n",
        "\n",
        "# === ประมวลผลทีละ Parquet file ===\n",
        "parquet_files = sorted(\n",
        "    [os.path.join(PARQUET_DIR, f) for f in os.listdir(PARQUET_DIR) if f.endswith(\".parquet\")],\n",
        "    key=lambda x: int(os.path.basename(x).split(\".\")[0])\n",
        ")\n",
        "\n",
        "num_workers = min(multiprocessing.cpu_count() * 2, 32)\n",
        "jsonl_lines = []\n",
        "total_successful = 0\n",
        "total_failed = 0\n",
        "total_skipped_short = 0\n",
        "total_skipped_long = 0\n",
        "total_skipped_invalid = 0\n",
        "total_scanned = 0\n",
        "\n",
        "print(f\"🚀 ประมวลผลทีละ Parquet file ด้วย {num_workers} workers...\")\n",
        "print(f\"   (โหลด → กรอง → แปลง → ปล่อย RAM → วนรอบ)\\n\")\n",
        "\n",
        "for pf_idx, pf in enumerate(parquet_files):\n",
        "    if MAX_CLIPS and total_successful >= MAX_CLIPS:\n",
        "        break\n",
        "    \n",
        "    pf_name = os.path.basename(pf)\n",
        "    \n",
        "    # --- ขั้น 1: โหลด Parquet + Pre-filter ---\n",
        "    table = pq.read_table(pf)\n",
        "    df_chunk = table.to_pandas()\n",
        "    del table\n",
        "    \n",
        "    chunk_items = []\n",
        "    chunk_skipped_short = 0\n",
        "    chunk_skipped_long = 0\n",
        "    chunk_skipped_invalid = 0\n",
        "    \n",
        "    for _, row in df_chunk.iterrows():\n",
        "        if MAX_CLIPS and (total_successful + len(chunk_items)) >= MAX_CLIPS:\n",
        "            break\n",
        "        \n",
        "        total_scanned += 1\n",
        "        audio_data = row['audio']\n",
        "        sentence = str(row['sentence']).strip()\n",
        "        utterance = str(row['utterance']).strip()\n",
        "        \n",
        "        if not sentence or not audio_data:\n",
        "            chunk_skipped_invalid += 1\n",
        "            continue\n",
        "        \n",
        "        if isinstance(audio_data, dict):\n",
        "            audio_bytes = audio_data.get('bytes', b'')\n",
        "        elif isinstance(audio_data, bytes):\n",
        "            audio_bytes = audio_data\n",
        "        else:\n",
        "            chunk_skipped_invalid += 1\n",
        "            continue\n",
        "        \n",
        "        if not audio_bytes or len(audio_bytes) < 100:\n",
        "            chunk_skipped_invalid += 1\n",
        "            continue\n",
        "        \n",
        "        verdict = pre_filter_by_size(audio_bytes, MIN_DURATION_SEC, MAX_DURATION_SEC)\n",
        "        if verdict == 'short':\n",
        "            chunk_skipped_short += 1\n",
        "            continue\n",
        "        if verdict == 'long':\n",
        "            chunk_skipped_long += 1\n",
        "            continue\n",
        "        \n",
        "        base_name = utterance.replace('.mp3', '').replace('.wav', '')\n",
        "        chunk_items.append((\n",
        "            audio_bytes, sentence, base_name,\n",
        "            OUTPUT_WAV_DIR, TARGET_SAMPLE_RATE, TARGET_CHANNELS,\n",
        "            MIN_DURATION_SEC, MAX_DURATION_SEC\n",
        "        ))\n",
        "    \n",
        "    # ปล่อย DataFrame ทันที (ลด RAM)\n",
        "    del df_chunk\n",
        "    gc.collect()\n",
        "    \n",
        "    total_skipped_short += chunk_skipped_short\n",
        "    total_skipped_long += chunk_skipped_long\n",
        "    total_skipped_invalid += chunk_skipped_invalid\n",
        "    \n",
        "    if not chunk_items:\n",
        "        print(f\"  📄 {pf_name}: ไม่มีไฟล์ผ่าน pre-filter\")\n",
        "        continue\n",
        "    \n",
        "    # --- ขั้น 2: แปลง MP3→WAV แบบ parallel ---\n",
        "    chunk_ok = 0\n",
        "    chunk_fail = 0\n",
        "    \n",
        "    with concurrent.futures.ProcessPoolExecutor(max_workers=num_workers) as executor:\n",
        "        futures = [executor.submit(process_audio_item, item) for item in chunk_items]\n",
        "        for future in concurrent.futures.as_completed(futures):\n",
        "            result = future.result()\n",
        "            if result is not None:\n",
        "                jsonl_lines.append(result)\n",
        "                chunk_ok += 1\n",
        "            else:\n",
        "                chunk_fail += 1\n",
        "    \n",
        "    total_successful += chunk_ok\n",
        "    total_failed += chunk_fail\n",
        "    \n",
        "    # --- ขั้น 3: ปล่อย RAM ของ MP3 bytes ทั้ง chunk ---\n",
        "    del chunk_items\n",
        "    gc.collect()\n",
        "    \n",
        "    ram_used = psutil.virtual_memory().percent\n",
        "    disk_free = psutil.disk_usage('/kaggle/working').free / (1024**3)\n",
        "    print(f\"  📄 {pf_name}: ✅{chunk_ok} ❌{chunk_fail} \"\n",
        "          f\"(สั้น:{chunk_skipped_short} ยาว:{chunk_skipped_long}) \"\n",
        "          f\"| รวม:{total_successful} | RAM:{ram_used:.0f}% | Disk:{disk_free:.1f}GB\")\n",
        "    \n",
        "    # ลบ Parquet file ที่ประมวลผลเสร็จแล้วเพื่อประหยัดดิสก์\n",
        "    os.remove(pf)\n",
        "    \n",
        "    # ถ้า disk เหลือน้อยกว่า 5GB ให้หยุด\n",
        "    if disk_free < 5.0:\n",
        "        print(f\"\\n⚠️ Disk เหลือ {disk_free:.1f}GB → หยุดเพื่อป้องกัน disk เต็ม!\")\n",
        "        break\n",
        "\n",
        "print(f\"\\n{'='*60}\")\n",
        "print(f\"✅ ผลรวม: สำเร็จ {total_successful} | ล้มเหลว {total_failed}\")\n",
        "print(f\"   สแกน {total_scanned} | สั้นเกิน {total_skipped_short} | ยาวเกิน {total_skipped_long} | invalid {total_skipped_invalid}\")\n",
        "\n",
        "total_duration = sum(json.loads(line)['duration'] for line in jsonl_lines)\n",
        "hours = total_duration / 3600\n",
        "print(f\"🕐 เวลาเสียงทั้งหมด: {total_duration:.1f} วินาที = {hours:.1f} ชั่วโมง\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 🧹 ส่วนที่ 4: เขียน JSONL & ลบ Parquet ที่เหลือ"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "os.makedirs(os.path.dirname(OUTPUT_JSONL), exist_ok=True)\n",
        "with open(OUTPUT_JSONL, \"w\", encoding=\"utf-8\") as f:\n",
        "    f.write(\"\\n\".join(jsonl_lines))\n",
        "    f.flush()\n",
        "    os.fsync(f.fileno())\n",
        "\n",
        "print(f\"✅ JSONL saved: {OUTPUT_JSONL} ({len(jsonl_lines)} entries)\")\n",
        "\n",
        "import shutil\n",
        "if os.path.exists(PARQUET_DIR):\n",
        "    shutil.rmtree(PARQUET_DIR)\n",
        "    print(\"🗑️ ลบ Parquet files ที่เหลือเรียบร้อย\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 🔊 ส่วนที่ 5: ดาวน์โหลด xcodec2 Audio Codec"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "XCODEC2_DIR = os.path.join(KAGGLE_WORKING, 'xcodec2_ckpt')\n",
        "XCODEC2_PATH = os.path.join(XCODEC2_DIR, 'checkpoint.pt')\n",
        "XCODEC2_URL = 'https://huggingface.co/HKUSTAudio/xcodec2/resolve/main/ckpt/epoch%3D4-step%3D1400000.ckpt'\n",
        "\n",
        "os.makedirs(XCODEC2_DIR, exist_ok=True)\n",
        "if not os.path.exists(XCODEC2_PATH):\n",
        "    subprocess.run([\n",
        "        'aria2c', '-x', '16', '-s', '16', '-k', '1M',\n",
        "        '-o', 'checkpoint.pt', '-d', XCODEC2_DIR, XCODEC2_URL\n",
        "    ], check=True)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 🧬 ส่วนที่ 6: Clone Repo + ติดตั้ง + Patch สำคัญ"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "REPO_URL = 'https://github.com/chalitbkb/Ovlyra.git'\n",
        "REPO_DIR = '/kaggle/working/Ovlyra'\n",
        "if not os.path.exists(REPO_DIR):\n",
        "    subprocess.run(['git', 'clone', REPO_URL, REPO_DIR], check=True)\n",
        "\n",
        "subprocess.run([sys.executable, '-m', 'pip', 'install', '-e', REPO_DIR, '--quiet'], check=True)\n",
        "\n",
        "import shutil\n",
        "CODEC_CONFIG_SRC = os.path.join(REPO_DIR, 'example', 'codec', 'model_config.json')\n",
        "CODEC_CONFIG_DST = os.path.join(XCODEC2_DIR, 'model_config.json')\n",
        "if not os.path.exists(CODEC_CONFIG_DST):\n",
        "    shutil.copy2(CODEC_CONFIG_SRC, CODEC_CONFIG_DST)\n",
        "    print(f'✅ Copied model_config.json → {CODEC_CONFIG_DST}')\n",
        "\n",
        "env_path = os.path.join(REPO_DIR, 'tts', 'training', 'environment.py')\n",
        "with open(env_path, 'r') as f:\n",
        "    env_code = f.read()\n",
        "env_code = env_code.replace(\n",
        "    'if not transformers_utils.is_flash_attn_2_available():',\n",
        "    'if False:  # [PATCHED] Disabled for T4 compatibility'\n",
        ")\n",
        "with open(env_path, 'w') as f:\n",
        "    f.write(env_code)\n",
        "print('✅ Patched environment.py: disabled flash_attn_2 check (T4 Safe!)')"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 🔬 ส่วนที่ 7: รัน Data Vectorization"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "VAL_SPLIT      = 0.05\n",
        "VEC_BATCH_SIZE  = 4     # ลดจาก 16 เพื่อป้องกัน CUDA OOM บน T4 (15GB VRAM)\n",
        "VEC_NUM_WORKERS = 4\n",
        "VECTORIZED_DIR = os.path.join(KAGGLE_WORKING, 'dataset', 'vectorized_th')\n",
        "os.makedirs(VECTORIZED_DIR, exist_ok=True)\n",
        "\n",
        "# ป้องกัน CUDA memory fragmentation\n",
        "os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:True'\n",
        "\n",
        "os.chdir(REPO_DIR)\n",
        "\n",
        "# ใช้ GPU เดียว (nproc=1) เพื่อไม่ให้โมเดล 635M params โหลดซ้ำบนทุก GPU\n",
        "# T4x2: แต่ละตัวมี 15GB → โหลดโมเดล+batch บน 1 ตัวก็เพียงพอ\n",
        "cmd = [\n",
        "    'torchrun', '--nproc_per_node=1',\n",
        "    'tools/data/data_vectorizer.py',\n",
        "    f'--codec_model_path={XCODEC2_PATH}',\n",
        "    f'--batch_size={VEC_BATCH_SIZE}',\n",
        "    f'--num_workers={VEC_NUM_WORKERS}',\n",
        "    f'--dataset_path={OUTPUT_JSONL}',\n",
        "    f'--output_dir={VECTORIZED_DIR}',\n",
        "    f'--val_split={VAL_SPLIT}'\n",
        "]\n",
        "# ไม่ใช้ --compile_model เพราะ torch.compile ใช้ VRAM เพิ่มอีกมาก\n",
        "subprocess.run(cmd, check=True)\n",
        "print('\\n✅ Data Vectorization complete!')"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 📦 ส่วนที่ 8: Merge Shards + Cleanup"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "os.chdir(REPO_DIR)\n",
        "subprocess.run([\n",
        "    sys.executable, 'tools/data/data_merger.py',\n",
        "    f'--dataset_path={VECTORIZED_DIR}',\n",
        "    '--remove_shards'\n",
        "], check=True)\n",
        "print('\\n✅ Shards merged!')"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "os.chdir(KAGGLE_WORKING)\n",
        "sample_wav_path = os.path.join(KAGGLE_WORKING, 'dataset', 'sample_prompt.wav')\n",
        "sample_txt_path = os.path.join(KAGGLE_WORKING, 'dataset', 'sample_transcript.txt')\n",
        "if os.path.exists(OUTPUT_JSONL):\n",
        "    with open(OUTPUT_JSONL, 'r', encoding='utf-8') as f:\n",
        "        first_line = f.readline().strip()\n",
        "        if first_line:\n",
        "            import json\n",
        "            import shutil\n",
        "            data = json.loads(first_line)\n",
        "            if os.path.exists(data['wav_path']):\n",
        "                shutil.copy2(data['wav_path'], sample_wav_path)\n",
        "                with open(sample_txt_path, 'w', encoding='utf-8') as txt_f:\n",
        "                    txt_f.write(data['transcript'])\n",
        "                print(f'🎤 ไฟล์ตัวอย่าง: {sample_wav_path}')\n",
        "\n",
        "if os.path.exists(PREP_DIR):\n",
        "    shutil.rmtree(PREP_DIR)\n",
        "    print('🗑️ ลบ prep/ เรียบร้อย — ประหยัดพื้นที่สำหรับ Notebook 2')\n",
        "\n",
        "dataset_dir = os.path.join(KAGGLE_WORKING, 'dataset')\n",
        "for root, dirs, files in os.walk(dataset_dir):\n",
        "    level = root.replace(dataset_dir, '').count(os.sep)\n",
        "    indent = ' ' * 2 * level\n",
        "    print(f'{indent}{os.path.basename(root)}/')\n",
        "    for f in files[:5]:\n",
        "        print(f'{indent}  {f}')\n",
        "    if len(files) > 5:\n",
        "        print(f'{indent}  ... และอีก {len(files)-5} ไฟล์')\n",
        "print('\\n✅ Output ใน dataset/ พร้อมสำหรับ Notebook 2 แล้ว!')"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "name": "python",
      "version": "3.10.12"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 4
}
