{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# 🚀 🇹🇭 เทรนโมเดล Ovlyra เสียงภาษาไทยบน Kaggle [Dual-T4 Optimized]\n",
        "\n",
        "**สมมติฐานสำคัญ**: Notebook นี้ใช้ Output (Data Vectorized) จาก `kagglenotebook1` ที่ถูก Add เข้ามาเป็น Input Data เรียบร้อยแล้ว\n",
        "\n",
        "เราจะทำการเทรนโมเดลแบบ **SFT** (Supervised Fine-Tuning) โดยใช้เทคนิค LoRA, DDP + 16-mixed precision (FP16 Native บน T4), และ **Patch FlashAttention2 → SDPA**\n",
        "\n",
        "**หมายเหตุ**: vLLM ถูกใช้เฉพาะ RLHF training เท่านั้น ไม่ได้ใช้ใน SFT pipeline นี้"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 📥 ส่วนที่ 1: Clone Ovlyra, ติดตั้ง Libraries, และ Login HF/W&B\n",
        "ต้องติดตั้ง package ก่อนเรียก `huggingface-cli` หรือ `import wandb` — ไม่งั้นจะ crash!"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "import os\n",
        "import subprocess\n",
        "import sys\n",
        "\n",
        "# ===== ✏️ ใส่ Token ของคุณตรงนี้ =====\n",
        "HF_TOKEN = \"hf_YourHuggingFaceTokenHere\"\n",
        "WANDB_API_KEY = \"YourWandBApiKeyHere\"\n",
        "WANDB_PROJECT = \"Thai_TTS_Project\"\n",
        "# =====================================\n",
        "\n",
        "# ตั้ง env vars ก่อน (ไม่ต้องติดตั้งอะไร)\n",
        "os.environ[\"HF_TOKEN\"] = HF_TOKEN\n",
        "os.environ[\"HUGGING_FACE_HUB_TOKEN\"] = HF_TOKEN\n",
        "os.environ[\"WANDB_API_KEY\"] = WANDB_API_KEY\n",
        "os.environ[\"WANDB_PROJECT\"] = WANDB_PROJECT\n",
        "os.environ[\"USER\"] = \"kaggle\"  # prevent KeyError in wandb setup\n",
        "os.environ[\"TOKENIZERS_PARALLELISM\"] = \"false\"\n",
        "\n",
        "# --- Step 1: Clone repo ---\n",
        "REPO_URL = \"https://github.com/chalitbkb/Ovlyra.git\"\n",
        "REPO_DIR = \"/kaggle/working/Ovlyra\"\n",
        "if not os.path.exists(REPO_DIR):\n",
        "    subprocess.run([\"git\", \"clone\", REPO_URL, REPO_DIR], check=True)\n",
        "\n",
        "# --- Step 2: Install Ovlyra + pythainlp (รวม transformers, wandb, torch etc.) ---\n",
        "os.chdir(REPO_DIR)\n",
        "subprocess.run([sys.executable, \"-m\", \"pip\", \"install\", \"-e\", \".\", \"--quiet\"], check=True)\n",
        "subprocess.run([sys.executable, \"-m\", \"pip\", \"install\", \"pythainlp>=5.0\", \"--quiet\"], check=True)\n",
        "print(\"✅ Ovlyra + pythainlp installed.\")\n",
        "\n",
        "# --- Step 3: Login (ต้องทำหลัง pip install เพราะ huggingface-cli + wandb มาจาก package) ---\n",
        "subprocess.run([sys.executable, \"-m\", \"huggingface_hub.commands.huggingface_cli\", \"login\", \"--token\", HF_TOKEN], check=True)\n",
        "print(\"✅ Hugging Face logged in.\")\n",
        "\n",
        "import wandb\n",
        "wandb.login(key=WANDB_API_KEY)\n",
        "print(\"✅ W&B logged in.\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 🛠️ ส่วนที่ 2: T4 Compatibility Patches\n",
        "การ์ดจอ T4 มีข้อจำกัดที่ต้องแก้ก่อนรัน:\n",
        "1. ไม่รองรับ **flash_attention_2** → แก้เป็น `sdpa` ใน modeling.py\n",
        "2. environment.py จะ crash ถ้าไม่มี flash_attn → ลบ check ออก\n",
        "3. NeMo ไม่รองรับ `ja` → เปลี่ยนเป็น graceful fallback"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ===== PATCH 1: สลับ FlashAttention2 ไปเป็น SDPA =====\n",
        "modeling_path = os.path.join(REPO_DIR, \"tts\", \"core\", \"modeling.py\")\n",
        "with open(modeling_path, \"r\") as f:\n",
        "    content = f.read()\n",
        "content = content.replace(\n",
        "    '_ATTN_IMPLEMENTATION = \"flash_attention_2\"',\n",
        "    '_ATTN_IMPLEMENTATION = \"sdpa\"'\n",
        ")\n",
        "with open(modeling_path, \"w\") as f:\n",
        "    f.write(content)\n",
        "print(\"✅ Patch 1: flash_attention_2 → sdpa\")\n",
        "\n",
        "# ===== PATCH 2: ลบ flash_attn_2 check ใน environment.py =====\n",
        "env_path = os.path.join(REPO_DIR, \"tts\", \"training\", \"environment.py\")\n",
        "with open(env_path, \"r\") as f:\n",
        "    env_code = f.read()\n",
        "env_code = env_code.replace(\n",
        "    'if not transformers_utils.is_flash_attn_2_available():',\n",
        "    'if False:  # [PATCHED] Disabled for T4 compatibility'\n",
        ")\n",
        "with open(env_path, \"w\") as f:\n",
        "    f.write(env_code)\n",
        "print(\"✅ Patch 2: environment.py flash_attn check disabled\")\n",
        "\n",
        "# ===== PATCH 3: แก้ NeMo normalizer crash เมื่อภาษา ja ไม่รองรับ =====\n",
        "tn_path = os.path.join(REPO_DIR, \"tts\", \"data\", \"text_normalization.py\")\n",
        "with open(tn_path, \"r\") as f:\n",
        "    tn_code = f.read()\n",
        "old_init = '''        self._normalize_text = {\n",
        "            lang: normalize.Normalizer(input_case=\"cased\", lang=lang)\n",
        "            for lang in self._nemo_languages\n",
        "        }'''\n",
        "new_init = '''        self._normalize_text = {}\n",
        "        for lang in self._nemo_languages:\n",
        "            try:\n",
        "                self._normalize_text[lang] = normalize.Normalizer(\n",
        "                    input_case=\"cased\", lang=lang\n",
        "                )\n",
        "            except (NotImplementedError, Exception) as e:\n",
        "                base_logging.warning(\n",
        "                    \"NeMo text normalization not available for \\'%s\\': %s. \"\n",
        "                    \"Text for this language will be passed through without \"\n",
        "                    \"normalization.\", lang, e,\n",
        "                )'''\n",
        "tn_code = tn_code.replace(old_init, new_init)\n",
        "with open(tn_path, \"w\") as f:\n",
        "    f.write(tn_code)\n",
        "print(\"✅ Patch 3: NeMo normalizer → graceful fallback for unsupported languages\")\n",
        "\n",
        "import torch\n",
        "gpu_count = torch.cuda.device_count()\n",
        "for i in range(gpu_count):\n",
        "    print(f\"  GPU {i}: {torch.cuda.get_device_name(i)} ({torch.cuda.get_device_properties(i).total_memory / 1e9:.1f} GB)\")\n",
        "print(f\"💡 Total GPUs: {gpu_count}\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### ⚙️ ส่วนที่ 3: สร้างไฟล์ Configuration (JSON)\n",
        "Config นี้ต้องตรงตามโครงสร้าง `ExperimentConfig` ใน `configuration.py` ทุกประการ:\n",
        "- 🔑 **ต้องมี**: `training`, `modeling`, `checkpointing`, `train_weighted_datasets`, `val_weighted_datasets`\n",
        "- 🔑 **modeling ต้องอยู่ใน `parameters`**: `codebook_size`, `model_name`, `max_seq_len`\n",
        "- 🎯 **precision:** 16-mixed (FP16 Native บน T4)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "import json\n",
        "\n",
        "# --- 📂 Paths & Dataset ---\n",
        "USER_KAGGLE  = 'dvwebdv'\n",
        "INPUT_NOTEBOOK_NAME = f'{USER_KAGGLE}/kagglenotebook1'\n",
        "INPUT_DATASET_DIR = f'/kaggle/input/notebooks/{INPUT_NOTEBOOK_NAME}'\n",
        "\n",
        "# --- 🔊 Audio Codec & Vectorized Data ---\n",
        "INPUT_XCODEC2_DIR  = f'{INPUT_DATASET_DIR}/xcodec2_ckpt'\n",
        "INPUT_XCODEC2_PATH = f'{INPUT_XCODEC2_DIR}/checkpoint.pt'\n",
        "VECTORIZED_DIR = f'{INPUT_DATASET_DIR}/dataset/vectorized_th'\n",
        "\n",
        "# 🛠️ สร้างโฟลเดอร์จำลอง (Symlink) สำหรับ XCODEC2 เพื่อให้สามารถแก้ไข model_config.json ได้ 100%\n",
        "XCODEC2_DIR = '/kaggle/working/xcodec2_ckpt'\n",
        "os.makedirs(XCODEC2_DIR, exist_ok=True)\n",
        "CODEC_MODEL_PATH = f'{XCODEC2_DIR}/checkpoint.pt'\n",
        "\n",
        "import shutil\n",
        "if os.path.exists(INPUT_XCODEC2_PATH):\n",
        "    # 1. Symlink ไฟล์ .pt (ประหยัดเวลา/พื้นที่ Disk ไม่ต้อง copy ขนาดไฟล์ 1.2GB จริง)\n",
        "    if not os.path.exists(CODEC_MODEL_PATH):\n",
        "        os.symlink(INPUT_XCODEC2_PATH, CODEC_MODEL_PATH)\n",
        "    \n",
        "    # 2. คัดลอก model_config.json ทับจาก Source Code (ป้องกันปัญหา Dataset เก่าจาก Notebook 1 ขาด config)\n",
        "    CONFIG_SRC = os.path.join(REPO_DIR, 'example/codec/model_config.json')\n",
        "    CONFIG_DST = os.path.join(XCODEC2_DIR, 'model_config.json')\n",
        "    if os.path.exists(CONFIG_SRC):\n",
        "        shutil.copy2(CONFIG_SRC, CONFIG_DST)\n",
        "    \n",
        "    size_mb = os.path.getsize(CODEC_MODEL_PATH) / (1024**2)\n",
        "    print(f'✅ xcodec2 Linked: {CODEC_MODEL_PATH} ({size_mb:.1f} MB)')\n",
        "else:\n",
        "    raise FileNotFoundError(f'❌ ไม่พบ xcodec2: {INPUT_XCODEC2_PATH}')\n",
        "\n",
        "if os.path.exists(VECTORIZED_DIR):\n",
        "    print(f'✅ Vectorized data: {VECTORIZED_DIR}')\n",
        "else:\n",
        "    raise FileNotFoundError(f'❌ ไม่พบ Vectorized data: {VECTORIZED_DIR}')\n",
        "\n",
        "print(f'\\n🎯 ทุกอย่างพร้อม! Codec: {CODEC_MODEL_PATH} | Data: {VECTORIZED_DIR}')\n",
        "\n",
        "# ====================================================================\n",
        "# 🎯 Round 6: Single-GPU + Porjai 50K dataset\n",
        "# ====================================================================\n",
        "# แก้ NCCL timeout / OOM:\n",
        "#   - devices=1 (ไม่ใช้ DDP → ไม่มี NCCL timeout)\n",
        "#   - max_seq_len: 2048 → 1024 (ลด VRAM ต่อ sample ลงครึ่ง)\n",
        "#   - gradient_accumulation: 16 → 32 (ชดเชย 1 GPU)\n",
        "#   - num_workers: 2 → 1 (ลด RAM/CPU)\n",
        "#   - keep_only_last_n_checkpoints: 3 (ประหยัด Disk)\n",
        "# ====================================================================\n",
        "\n",
        "config = {\n",
        "    \"training\": {\n",
        "        \"seed\": 42,\n",
        "        \"logging_steps\": 10,\n",
        "        \"eval_steps\": 100,\n",
        "        \"gradient_accumulation_steps\": 32,\n",
        "        \"gradient_clip_value\": 0.5,\n",
        "        \"learning_rate\": 1.5e-5,\n",
        "        \"betas\": [0.9, 0.95],\n",
        "        \"warmup_ratio\": 0.1,\n",
        "        \"batch_size\": 1,\n",
        "        \"weight_decay\": 0.1,\n",
        "        \"precision\": \"16-mixed\",\n",
        "        \"strategy\": \"auto\",\n",
        "        \"gradient_checkpointing\": True,\n",
        "        \"num_workers\": 1\n",
        "    },\n",
        "    \"modeling\": {\n",
        "        \"parameters\": {\n",
        "            \"codebook_size\": 65536,\n",
        "            \"max_seq_len\": 1024,\n",
        "            \"model_name\": \"meta-llama/Llama-3.2-1B-Instruct\",\n",
        "            \"enable_text_normalization\": True\n",
        "        }\n",
        "    },\n",
        "    \"checkpointing\": {\n",
        "        \"save_steps\": 100,\n",
        "        \"collect_health_stats\": False,\n",
        "        \"save_intermediate_generations\": False,\n",
        "        \"only_load_model_weights\": True,\n",
        "        \"keep_only_last_n_checkpoints\": 3\n",
        "    },\n",
        "    \"train_weighted_datasets\": {\n",
        "        VECTORIZED_DIR: 1.0\n",
        "    },\n",
        "    \"val_weighted_datasets\": {\n",
        "        VECTORIZED_DIR: 1.0\n",
        "    },\n",
        "    \"dataset\": {\n",
        "        \"allowed_languages\": [\"th\"],\n",
        "        \"min_dnsmos_score\": 0.0,\n",
        "        \"min_sample_rate\": 0,\n",
        "        \"enable_rlhf_training\": False,\n",
        "        \"min_audio_duration\": 0.5\n",
        "    },\n",
        "    \"lora\": {\n",
        "        \"task_type\": \"CAUSAL_LM\",\n",
        "        \"r\": 8,\n",
        "        \"lora_alpha\": 16,\n",
        "        \"target_modules\": [\"q_proj\", \"k_proj\", \"v_proj\", \"o_proj\"],\n",
        "        \"lora_dropout\": 0.1,\n",
        "        \"bias\": \"none\",\n",
        "        \"modules_to_save\": [\"embed_tokens\", \"lm_head\"]\n",
        "    }\n",
        "}\n",
        "\n",
        "config_path = os.path.join(REPO_DIR, \"th_sft_t4.json\")\n",
        "with open(config_path, \"w\") as f:\n",
        "    json.dump(config, f, indent=2)\n",
        "\n",
        "print(f\"✅ Saved config to {config_path}\")\n",
        "print(f\"📂 Dataset dir: {VECTORIZED_DIR}\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 🏃‍♂️ ส่วนที่ 4: เริ่มต้นกระบวนการ Training\n",
        "ใช้คำสั่ง `fabric run` เพื่อกระตุ้น GPU ทั้ง 2 ใบให้ทำงานประสานกัน\n",
        "\n",
        "- `--experiment_dir` = ที่เก็บ checkpoint (main.py จะสร้าง subdirectory ตาม `--run_name`)\n",
        "- `--use_wandb` = เปิดล็อก training metrics ไปที่ Weights & Biases"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "os.chdir(REPO_DIR)\n",
        "\n",
        "# ป้องกัน CUDA memory fragmentation\n",
        "os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:True'\n",
        "\n",
        "# ใช้ GPU เดียว (devices=1) เพื่อ:\n",
        "# 1. ป้องกัน NCCL timeout (ถ้า 1 GPU OOM → DDP ทั้งหมดพัง)\n",
        "# 2. ประหยัด VRAM (ไม่ต้องโหลดโมเดลซ้ำ 2 ตัว)\n",
        "# gradient_accumulation=32 ชดเชยที่ใช้ 1 GPU แทน 2\n",
        "subprocess.run([\n",
        "    \"fabric\", \"run\", \"--devices=1\",\n",
        "    \"tts/training/main.py\",\n",
        "    \"--config_path=th_sft_t4.json\",\n",
        "    \"--experiment_dir=/kaggle/working/experiments\",\n",
        "    \"--run_name=th-sft-t4\",\n",
        "    \"--project_name=Thai_TTS_Project\",\n",
        "    \"--use_wandb\"\n",
        "], check=True)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 💾 ส่วนที่ 5: Convert Checkpoint เป็น Safetensors สำหรับเสิร์ฟ\n",
        "รวม LoRA Adapter เข้ากับ Base Model (Merge) เพื่อให้แชร์แล้วใช้ต่อได้ง่าย\n",
        "\n",
        "checkpoint directory จะอยู่ที่ `/kaggle/working/experiments/th-sft-t4/`"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "import glob\n",
        "\n",
        "os.chdir(REPO_DIR)\n",
        "EXPERIMENT_DIR = \"/kaggle/working/experiments/th-sft-t4\"\n",
        "export_dir = \"/kaggle/working/th_sft_merged_model\"\n",
        "\n",
        "# หา checkpoint ล่าสุด (final_model.pt หรือ checkpoint_N.pt)\n",
        "final_model = os.path.join(EXPERIMENT_DIR, \"final_model.pt\")\n",
        "if os.path.exists(final_model):\n",
        "    model_pt = final_model\n",
        "    print(f\"⭐ Found final_model.pt\")\n",
        "else:\n",
        "    # หา checkpoint เฉพาะ step ล่าสุด\n",
        "    chkpt_files = glob.glob(os.path.join(EXPERIMENT_DIR, \"checkpoint_*.pt\"))\n",
        "    if chkpt_files:\n",
        "        model_pt = sorted(chkpt_files, key=lambda x: int(x.split(\"_\")[-1].replace(\".pt\", \"\")))[-1]\n",
        "        print(f\"⭐ Found checkpoint: {model_pt}\")\n",
        "    else:\n",
        "        model_pt = None\n",
        "        print(\"❌ ไม่พบ Checkpoint\")\n",
        "\n",
        "if model_pt:\n",
        "    subprocess.run([\n",
        "        sys.executable, \"tools/serving/convert_checkpoint.py\",\n",
        "        f\"--checkpoint_path={model_pt}\",\n",
        "        f\"--output_path={export_dir}\",\n",
        "        \"--merge_lora\"\n",
        "    ], check=True)\n",
        "    print(f\"\\n🎉 All done! โหลดโฟลเดอร์ {export_dir} ไปรัน Inference ได้เลย!\")\n",
        "\n",
        "    # 🧹 ลบ Checkpoint ระหว่างทางเพื่อประหยัดพื้นที่ดิสก์\n",
        "    print(\"\\n🗑️ กำลังลบ Checkpoints ระหว่างทางเพื่อคืนพื้นที่ดิสก์...\")\n",
        "    for ckpt in glob.glob(os.path.join(EXPERIMENT_DIR, \"checkpoint_*.pt\")):\n",
        "        # ถ้ามี final_model.pt หรือโมเดลอื่นที่ไม่ใช่ตัวที่เพิ่งแปลง\n",
        "        if os.path.exists(final_model) or ckpt != model_pt:\n",
        "            try:\n",
        "                if os.path.isdir(ckpt):\n",
        "                    import shutil\n",
        "                    shutil.rmtree(ckpt)\n",
        "                else:\n",
        "                    os.remove(ckpt)\n",
        "            except Exception:\n",
        "                pass\n",
        "    print(\"✅ ลบเรียบร้อย! (เหลือเก็บไว้เฉพาะ final_model.pt และโมเดลที่ Convert เสร็จแล้ว)\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 🎤 ส่วนที่ 6: ทดสอบโคลนเสียงสด! (Inference & Voice Cloning)\n",
        "เวลาแห่งความตื่นเต้น! เราจะทดสอบโมเดลที่เพิ่งเทรนเสร็จ\n",
        "โดยป้อนไฟล์เสียงตัวอย่างสั้นๆ (Prompt) + ข้อความที่ต้องการให้พูด\n",
        "แล้วฟังผลลัพธ์กันสดๆ!\n",
        "\n",
        "> 💡 **สำหรับ Zero-Shot Voice Cloning:**\n",
        "> แค่เปลี่ยนไฟล์เสียง Prompt เป็นเสียงของคนที่คุณต้องการโคลน (3-10 วินาที)\n",
        "> โมเดลจะเลียนแบบสำเนียงและโทนเสียงให้อัตโนมัติ!"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# เตรียมไฟล์เสียงตัวอย่างสำหรับทดสอบ (Zero-Shot Voice Cloning)\n",
        "# -------------------------------------------------------------\n",
        "import os\n",
        "\n",
        "# 1. ใส่ Path ของไฟล์เสียงของคุณเอง (3-10 วินาที ชัดเจน ไม่มีเสียงรบกวน)\n",
        "USER_PROMPT_WAV = f'/kaggle/input/datasets/{USER_KAGGLE}/my-voice/my_voice.wav'\n",
        "USER_TRANSCRIPT = 'ข้อความที่คุณพูดในไฟล์เสียง'\n",
        "\n",
        "# --- ระบบตรวจสอบอัตโนมัติ ---\n",
        "DEFAULT_PROMPT_WAV = f'{INPUT_DATASET_DIR}/dataset/sample_prompt.wav'\n",
        "DEFAULT_TXT_PATH = f'{INPUT_DATASET_DIR}/dataset/sample_transcript.txt'\n",
        "\n",
        "if os.path.exists(USER_PROMPT_WAV):\n",
        "    PROMPT_WAV = USER_PROMPT_WAV\n",
        "    PROMPT_TRANSCRIPTION = USER_TRANSCRIPT\n",
        "    print('✅ พบไฟล์เสียงของคุณเองที่จะใช้โคลน')\n",
        "elif os.path.exists(DEFAULT_PROMPT_WAV):\n",
        "    PROMPT_WAV = DEFAULT_PROMPT_WAV\n",
        "    try:\n",
        "        with open(DEFAULT_TXT_PATH, 'r', encoding='utf-8') as f:\n",
        "            PROMPT_TRANSCRIPTION = f.read().strip()\n",
        "    except Exception:\n",
        "        PROMPT_TRANSCRIPTION = 'สวัสดีครับ'\n",
        "    print('⚠️ ไม่พบไฟล์เสียงของคุณ, ระบบจะดึงไฟล์เสียงตัวอย่าง (Sample) จาก Notebook 1 มาทดสอบแทน')\n",
        "else:\n",
        "    raise FileNotFoundError(f'❌ ไม่พบไฟล์เสียง Prompt ใดๆ เลย, ระบบต้องการไฟล์เพื่อใช้ Inference!')\n",
        "\n",
        "# 3. ข้อความใหม่ที่ต้องการให้โมเดลพูดเลียนแบบเสียง\n",
        "TEXT_TO_SPEAK = 'สวัสดีครับ ออฟไลร่า โมเดลเสียงภาษาไทยที่คล้ายธรรมชาติที่สุด พร้อมใช้งานแล้วครับ!'\n",
        "\n",
        "OUTPUT_WAV = '/kaggle/working/cloned_voice_output.wav'\n",
        "\n",
        "print(f'\\n🎵 Using Prompt Audio: {PROMPT_WAV}')\n",
        "print(f'📝 Prompt Transcription: {PROMPT_TRANSCRIPTION}')\n",
        "print(f'💬 Text to Speak: {TEXT_TO_SPEAK}')"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# 🎙️ รัน Inference — สร้างเสียงโคลนนิ่ง!\n",
        "# ใช้ xcodec2 checkpoint ทั้ง Encoder + Decoder (ตามที่ README.md แนะนำ)\n",
        "print('\\n⏳ กำลังประมวลผล... สร้างเสียงโคลนนิ่ง... (อาจใช้เวลาประมาณ 10-30 วินาที)')\n",
        "\n",
        "os.chdir(REPO_DIR)\n",
        "\n",
        "cmd = [\n",
        "    sys.executable, 'tools/serving/inference.py',\n",
        "    f'--model_checkpoint_path={export_dir}',\n",
        "    f'--audio_encoder_path={CODEC_MODEL_PATH}',\n",
        "    f'--audio_decoder_path={CODEC_MODEL_PATH}',\n",
        "    f'--prompt_wav_path={PROMPT_WAV}',\n",
        "    f'--prompt_transcription={PROMPT_TRANSCRIPTION}',\n",
        "    f'--text={TEXT_TO_SPEAK}',\n",
        "    f'--output_path={OUTPUT_WAV}',\n",
        "    '--seed=42'\n",
        "]\n",
        "\n",
        "if os.path.exists(export_dir) and os.path.exists(PROMPT_WAV):\n",
        "    try:\n",
        "        subprocess.run(cmd, check=True)\n",
        "        print(f'\\n🎉 Output saved to: {OUTPUT_WAV}')\n",
        "    except subprocess.CalledProcessError as e:\n",
        "        print(f'\\n❌ เกิดข้อผิดพลาดระหว่างรัน Inference: {e}')\n",
        "else:\n",
        "    if not os.path.exists(export_dir):\n",
        "        print(f'\\n❌ ไม่พบโฟลเดอร์โมเดล: {export_dir}')\n",
        "    if not os.path.exists(PROMPT_WAV):\n",
        "        print(f'\\n❌ ไม่พบไฟล์เสียง Prompt: {PROMPT_WAV}')\n",
        "        print('💡 กรุณาอัปโหลดไฟล์เสียงเป็น Dataset แล้วแก้ค่า PROMPT_WAV ด้านบน')"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# 🔊 เล่นเสียงผลลัพธ์ใน Notebook!\n",
        "import IPython.display as ipd\n",
        "\n",
        "if os.path.exists(OUTPUT_WAV):\n",
        "    file_size = os.path.getsize(OUTPUT_WAV)\n",
        "    if file_size > 0:\n",
        "        print(f'🎧 ไฟล์เสียงขนาด: {file_size/1024:.1f} KB')\n",
        "        print('กดปุ่ม Play ด้านล่างเพื่อฟังผลลัพธ์!')\n",
        "        display(ipd.Audio(OUTPUT_WAV))\n",
        "    else:\n",
        "        print('⚠️ ไฟล์เสียงว่างเปล่า! โมเดลอาจยังเทรนไม่พอ')\n",
        "else:\n",
        "    print('❌ ไม่พบไฟล์เสียง output')"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "name": "python",
      "version": "3.10.12"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 4
}
