{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# ⚡ 🇹🇭 เตรียมชุดข้อมูลเสียงภาษาไทย (Porjai Central) [Speedrun Edition]\n",
        "\n",
        "ดาวน์โหลดชุดข้อมูล **CMKL/Porjai-Thai-voice-dataset-central** (335,674 ตัวอย่าง!)\n",
        "ผ่าน **Parquet API** ที่เร็วที่สุด แล้วแปลงเป็น WAV + JSONL สำหรับ Notebook 2\n",
        "\n",
        "**เทคนิค:**\n",
        "1. `Parquet API`: ดาวน์โหลด dataset ทั้งหมดผ่าน Parquet files (เร็วกว่า Rows API 100x)\n",
        "2. `Pre-filter Duration`: ประเมิน duration จาก MP3 bytes **ก่อน**แปลง — ข้ามไฟล์ที่สั้น/ยาวเกิน\n",
        "3. `Parallel FFmpeg`: แปลง MP3→WAV ด้วย multi-process\n",
        "4. `Accurate Duration`: คำนวณ duration จริงจากไฟล์ WAV หลังแปลง\n",
        "\n",
        "**โครงสร้างโฟลเดอร์:**\n",
        "- `prep/` — ข้อมูลดิบชั่วคราว (Parquet, MP3, WAV, JSONL) จะถูกลบเมื่อเสร็จ\n",
        "- `dataset/` — เฉพาะ vectorized output ที่ Notebook 2 ต้องการเท่านั้น"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ติดตั้ง dependencies\n",
        "!apt-get update -qq && apt-get install -y -qq aria2\n",
        "!pip install pandas pyarrow requests psutil tqdm -q"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### ⚙️ ส่วนที่ 1: ตั้งค่าระบบ (Configuration)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "import json\n",
        "import os\n",
        "import io\n",
        "import subprocess\n",
        "import sys\n",
        "import concurrent.futures\n",
        "import multiprocessing\n",
        "import psutil\n",
        "import pandas as pd\n",
        "import requests\n",
        "from tqdm import tqdm\n",
        "\n",
        "os.environ[\"TOKENIZERS_PARALLELISM\"] = \"false\"\n",
        "\n",
        "KAGGLE_WORKING = \"/kaggle/working\"\n",
        "PREP_DIR       = os.path.join(KAGGLE_WORKING, \"prep\")\n",
        "PARQUET_DIR    = os.path.join(PREP_DIR, \"parquet\")\n",
        "OUTPUT_WAV_DIR = os.path.join(PREP_DIR, \"th_wavs\")\n",
        "OUTPUT_JSONL   = os.path.join(PREP_DIR, \"train.jsonl\")\n",
        "\n",
        "TARGET_SAMPLE_RATE = 24000\n",
        "TARGET_CHANNELS    = 1\n",
        "\n",
        "# === กรอง Duration (วินาที) ===\n",
        "MIN_DURATION_SEC = 0.5   # ข้ามไฟล์ที่สั้นกว่า 0.5 วินาที\n",
        "MAX_DURATION_SEC = 30.0  # ข้ามไฟล์ที่ยาวกว่า 30 วินาที\n",
        "\n",
        "# === จำนวนตัวอย่างที่ต้องการ ===\n",
        "# ตั้งเป็น None เพื่อใช้ทั้ง 335,674 ตัวอย่าง\n",
        "# หรือตั้งเป็นตัวเลข เช่น 50000 เพื่อจำกัด\n",
        "MAX_CLIPS = 50000\n",
        "\n",
        "# URL ของ Parquet files สำหรับ Porjai dataset\n",
        "PARQUET_BASE_URL = \"https://huggingface.co/api/datasets/CMKL/Porjai-Thai-voice-dataset-central/parquet/default/train\"\n",
        "\n",
        "print(f\"📋 Config: MAX_CLIPS={MAX_CLIPS}, SR={TARGET_SAMPLE_RATE}Hz\")\n",
        "print(f\"📋 Duration filter: {MIN_DURATION_SEC}s - {MAX_DURATION_SEC}s\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 📥 ส่วนที่ 2: ดาวน์โหลด Parquet Files ด้วย Aria2"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "os.makedirs(PARQUET_DIR, exist_ok=True)\n",
        "\n",
        "# ดึงรายการ Parquet URLs\n",
        "print(\"🔍 กำลังดึงรายการ Parquet files...\")\n",
        "response = requests.get(PARQUET_BASE_URL)\n",
        "response.raise_for_status()\n",
        "parquet_urls = response.json()\n",
        "print(f\"📦 พบ {len(parquet_urls)} Parquet files\")\n",
        "\n",
        "# ดาวน์โหลดทุก Parquet file ด้วย aria2\n",
        "for i, url in enumerate(parquet_urls):\n",
        "    filename = f\"{i}.parquet\"\n",
        "    filepath = os.path.join(PARQUET_DIR, filename)\n",
        "    if not os.path.exists(filepath):\n",
        "        print(f\"⬇️  Downloading {filename} ({i+1}/{len(parquet_urls)})...\")\n",
        "        subprocess.run([\n",
        "            \"aria2c\", \"-x\", \"16\", \"-s\", \"16\", \"-k\", \"1M\",\n",
        "            \"--console-log-level=error\",\n",
        "            \"-o\", filename, \"-d\", PARQUET_DIR, url\n",
        "        ], check=True)\n",
        "    else:\n",
        "        print(f\"✅ {filename} already exists\")\n",
        "\n",
        "print(f\"\\n✅ ดาวน์โหลด Parquet files ทั้ง {len(parquet_urls)} ไฟล์เสร็จสิ้น!\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 🔍 ส่วนที่ 3: อ่าน Parquet + Pre-filter Duration ก่อนแปลง\n",
        "ใช้ `ffprobe` pipe เพื่อวัด duration จาก MP3 bytes **ก่อน**แปลงเป็น WAV\n",
        "→ ข้ามไฟล์ที่ไม่ผ่านเกณฑ์ทันที ไม่เสียเวลาแปลง!"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "import pyarrow.parquet as pq\n",
        "\n",
        "os.makedirs(OUTPUT_WAV_DIR, exist_ok=True)\n",
        "\n",
        "def estimate_mp3_duration(audio_bytes):\n",
        "    \"\"\"ประเมิน duration ของ MP3 จาก bytes ด้วย ffprobe pipe (เร็วมาก ไม่ต้องแปลง)\"\"\"\n",
        "    try:\n",
        "        proc = subprocess.run(\n",
        "            ['ffprobe', '-v', 'quiet', '-print_format', 'json',\n",
        "             '-show_format', '-i', 'pipe:0'],\n",
        "            input=audio_bytes,\n",
        "            capture_output=True,\n",
        "            timeout=10\n",
        "        )\n",
        "        if proc.returncode == 0:\n",
        "            info = json.loads(proc.stdout)\n",
        "            return float(info.get('format', {}).get('duration', 0))\n",
        "    except Exception:\n",
        "        pass\n",
        "    return -1.0  # ไม่สามารถวัดได้\n",
        "\n",
        "\n",
        "print(\"📖 กำลังอ่าน Parquet files + กรอง duration...\")\n",
        "all_rows = []\n",
        "skipped_short = 0\n",
        "skipped_long = 0\n",
        "skipped_invalid = 0\n",
        "\n",
        "# อ่านทุก Parquet file\n",
        "parquet_files = sorted(\n",
        "    [os.path.join(PARQUET_DIR, f) for f in os.listdir(PARQUET_DIR) if f.endswith(\".parquet\")],\n",
        "    key=lambda x: int(os.path.basename(x).split(\".\")[0])\n",
        ")\n",
        "\n",
        "total_collected = 0\n",
        "total_scanned = 0\n",
        "for pf in parquet_files:\n",
        "    if MAX_CLIPS and total_collected >= MAX_CLIPS:\n",
        "        break\n",
        "    \n",
        "    table = pq.read_table(pf)\n",
        "    df_chunk = table.to_pandas()\n",
        "    \n",
        "    for idx, row in df_chunk.iterrows():\n",
        "        if MAX_CLIPS and total_collected >= MAX_CLIPS:\n",
        "            break\n",
        "        \n",
        "        total_scanned += 1\n",
        "        \n",
        "        # ดึง audio bytes จาก Parquet\n",
        "        audio_data = row['audio']\n",
        "        sentence = str(row['sentence']).strip()\n",
        "        utterance = str(row['utterance']).strip()\n",
        "        \n",
        "        # ข้ามถ้าไม่มีข้อความหรือเสียง\n",
        "        if not sentence or not audio_data:\n",
        "            skipped_invalid += 1\n",
        "            continue\n",
        "        \n",
        "        # audio_data อาจเป็น dict {'bytes': ..., 'path': ...} หรือ bytes โดยตรง\n",
        "        if isinstance(audio_data, dict):\n",
        "            audio_bytes = audio_data.get('bytes', b'')\n",
        "        elif isinstance(audio_data, bytes):\n",
        "            audio_bytes = audio_data\n",
        "        else:\n",
        "            skipped_invalid += 1\n",
        "            continue\n",
        "        \n",
        "        if not audio_bytes or len(audio_bytes) < 100:\n",
        "            skipped_invalid += 1\n",
        "            continue\n",
        "        \n",
        "        # ====== PRE-FILTER: วัด duration จาก MP3 ก่อนแปลง ======\n",
        "        mp3_duration = estimate_mp3_duration(audio_bytes)\n",
        "        \n",
        "        if mp3_duration >= 0 and mp3_duration < MIN_DURATION_SEC:\n",
        "            skipped_short += 1\n",
        "            continue\n",
        "        \n",
        "        if mp3_duration > MAX_DURATION_SEC:\n",
        "            skipped_long += 1\n",
        "            continue\n",
        "        # ========================================================\n",
        "        \n",
        "        # ใช้ utterance เป็นชื่อไฟล์\n",
        "        base_name = utterance.replace('.mp3', '').replace('.wav', '')\n",
        "        \n",
        "        all_rows.append({\n",
        "            'audio_bytes': audio_bytes,\n",
        "            'sentence': sentence,\n",
        "            'base_name': base_name,\n",
        "            'mp3_duration': mp3_duration,\n",
        "        })\n",
        "        total_collected += 1\n",
        "    \n",
        "    del df_chunk, table\n",
        "    \n",
        "    print(f\"  📄 {os.path.basename(pf)}: สแกน {total_scanned} | ผ่าน {total_collected} \"\n",
        "          f\"| ข้ามสั้น {skipped_short} | ข้ามยาว {skipped_long} | invalid {skipped_invalid}\")\n",
        "\n",
        "print(f\"\\n✅ กรองเสร็จ: {total_collected} ผ่าน จาก {total_scanned} ที่สแกน\")\n",
        "print(f\"   ❌ ข้ามเพราะสั้นเกิน (<{MIN_DURATION_SEC}s): {skipped_short}\")\n",
        "print(f\"   ❌ ข้ามเพราะยาวเกิน (>{MAX_DURATION_SEC}s): {skipped_long}\")\n",
        "print(f\"   ❌ ข้ามเพราะข้อมูลไม่ถูกต้อง: {skipped_invalid}\")\n",
        "print(f\"   ✅ พร้อมแปลง: {total_collected} ตัวอย่าง\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### ⚡ ส่วนที่ 4: แปลง MP3 → WAV ด้วย Parallel FFmpeg + คำนวณ Duration แม่นยำ\n",
        "ตอนนี้แปลงเฉพาะไฟล์ที่ผ่านการกรองแล้วเท่านั้น! ไม่เสียเวลาแปลงไฟล์ที่ไม่ผ่าน"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "def process_audio_item(item):\n",
        "    \"\"\"แปลง MP3 bytes เป็น WAV (เฉพาะไฟล์ที่ผ่านกรองแล้ว) และคำนวณ duration แม่นยำ\"\"\"\n",
        "    audio_bytes = item['audio_bytes']\n",
        "    sentence = item['sentence']\n",
        "    base_name = item['base_name']\n",
        "    \n",
        "    wav_filename = f\"{base_name}.wav\"\n",
        "    wav_path = os.path.join(OUTPUT_WAV_DIR, wav_filename)\n",
        "    \n",
        "    # แปลง MP3 → WAV ด้วย FFmpeg pipe\n",
        "    process = subprocess.Popen([\n",
        "        \"ffmpeg\", \"-y\", \"-i\", \"pipe:0\",\n",
        "        \"-ar\", str(TARGET_SAMPLE_RATE),\n",
        "        \"-ac\", str(TARGET_CHANNELS),\n",
        "        \"-sample_fmt\", \"s16\",\n",
        "        \"-threads\", \"1\",\n",
        "        wav_path\n",
        "    ], stdin=subprocess.PIPE, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)\n",
        "    process.communicate(input=audio_bytes)\n",
        "    \n",
        "    if process.returncode != 0 or not os.path.exists(wav_path):\n",
        "        return None\n",
        "    \n",
        "    # คำนวณ duration อย่างแม่นยำจากไฟล์ WAV จริง\n",
        "    # WAV 16-bit mono: data_bytes = (file_size - 44_header) / (2_bytes_per_sample)\n",
        "    try:\n",
        "        file_size = os.path.getsize(wav_path)\n",
        "        data_bytes = file_size - 44\n",
        "        num_samples = data_bytes // 2\n",
        "        duration = num_samples / TARGET_SAMPLE_RATE\n",
        "    except Exception:\n",
        "        duration = 0.0\n",
        "    \n",
        "    # Double-check: กรองอีกครั้งด้วย duration จาก WAV จริง (แม่นยำกว่า MP3 estimate)\n",
        "    if duration < MIN_DURATION_SEC or duration > MAX_DURATION_SEC:\n",
        "        if os.path.exists(wav_path):\n",
        "            os.remove(wav_path)\n",
        "        return None\n",
        "    \n",
        "    return json.dumps({\n",
        "        \"transcript\": sentence,\n",
        "        \"language\": \"th\",\n",
        "        \"wav_path\": wav_path,\n",
        "        \"duration\": round(duration, 3),\n",
        "        \"sample_rate\": TARGET_SAMPLE_RATE\n",
        "    }, ensure_ascii=False)\n",
        "\n",
        "\n",
        "# รัน parallel conversion (เฉพาะไฟล์ที่ผ่านกรองแล้ว!)\n",
        "num_workers = min(multiprocessing.cpu_count() * 2, 32)\n",
        "print(f\"🚀 เริ่มแปลง {len(all_rows)} ไฟล์ (ที่ผ่านกรองแล้ว) ด้วย {num_workers} workers...\")\n",
        "\n",
        "jsonl_lines = []\n",
        "successful = 0\n",
        "failed = 0\n",
        "\n",
        "with concurrent.futures.ProcessPoolExecutor(max_workers=num_workers) as executor:\n",
        "    futures = [executor.submit(process_audio_item, item) for item in all_rows]\n",
        "    \n",
        "    pbar = tqdm(total=len(futures), desc=\"Converting MP3→WAV\")\n",
        "    for future in concurrent.futures.as_completed(futures):\n",
        "        result = future.result()\n",
        "        if result is not None:\n",
        "            jsonl_lines.append(result)\n",
        "            successful += 1\n",
        "        else:\n",
        "            failed += 1\n",
        "        pbar.update(1)\n",
        "    pbar.close()\n",
        "\n",
        "# ปล่อย memory ของ audio bytes\n",
        "del all_rows\n",
        "\n",
        "print(f\"\\n✅ แปลงสำเร็จ: {successful} | ล้มเหลว: {failed}\")\n",
        "\n",
        "# คำนวณเวลาทั้งหมด\n",
        "total_duration = 0\n",
        "for line in jsonl_lines:\n",
        "    data = json.loads(line)\n",
        "    total_duration += data['duration']\n",
        "hours = total_duration / 3600\n",
        "print(f\"🕐 เวลาเสียงทั้งหมด: {total_duration:.1f} วินาที = {hours:.1f} ชั่วโมง\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 🧹 ส่วนที่ 5: เขียน JSONL & ลบไฟล์ Parquet ดิบ"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "os.makedirs(os.path.dirname(OUTPUT_JSONL), exist_ok=True)\n",
        "with open(OUTPUT_JSONL, \"w\", encoding=\"utf-8\") as f:\n",
        "    f.write(\"\\n\".join(jsonl_lines))\n",
        "    f.flush()\n",
        "    os.fsync(f.fileno())\n",
        "\n",
        "print(f\"✅ JSONL saved: {OUTPUT_JSONL} ({len(jsonl_lines)} entries)\")\n",
        "\n",
        "# ลบ Parquet files เพื่อประหยัดพื้นที่\n",
        "import shutil\n",
        "if os.path.exists(PARQUET_DIR):\n",
        "    shutil.rmtree(PARQUET_DIR)\n",
        "    print(\"🗑️ ลบ Parquet files เรียบร้อย\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 🔊 ส่วนที่ 6: ดาวน์โหลด xcodec2 Audio Codec"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "XCODEC2_DIR = os.path.join(KAGGLE_WORKING, 'xcodec2_ckpt')\n",
        "XCODEC2_PATH = os.path.join(XCODEC2_DIR, 'checkpoint.pt')\n",
        "XCODEC2_URL = 'https://huggingface.co/HKUSTAudio/xcodec2/resolve/main/ckpt/epoch%3D4-step%3D1400000.ckpt'\n",
        "\n",
        "os.makedirs(XCODEC2_DIR, exist_ok=True)\n",
        "if not os.path.exists(XCODEC2_PATH):\n",
        "    subprocess.run([\n",
        "        'aria2c', '-x', '16', '-s', '16', '-k', '1M',\n",
        "        '-o', 'checkpoint.pt', '-d', XCODEC2_DIR, XCODEC2_URL\n",
        "    ], check=True)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 🧬 ส่วนที่ 7: Clone Repo + ติดตั้ง + Patch สำคัญ\n",
        "⚠️ ต้อง Patch: ลบการตรวจสอบ flash_attn_2 ใน `environment.py` (T4 ไม่มี flash-attn แต่ Vectorizer ไม่ได้ใช้งานมันจริง)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "REPO_URL = 'https://github.com/chalitbkb/Ovlyra.git'\n",
        "REPO_DIR = '/kaggle/working/Ovlyra'\n",
        "if not os.path.exists(REPO_DIR):\n",
        "    subprocess.run(['git', 'clone', REPO_URL, REPO_DIR], check=True)\n",
        "\n",
        "subprocess.run([sys.executable, '-m', 'pip', 'install', '-e', REPO_DIR, '--quiet'], check=True)\n",
        "\n",
        "import shutil\n",
        "CODEC_CONFIG_SRC = os.path.join(REPO_DIR, 'example', 'codec', 'model_config.json')\n",
        "CODEC_CONFIG_DST = os.path.join(XCODEC2_DIR, 'model_config.json')\n",
        "if not os.path.exists(CODEC_CONFIG_DST):\n",
        "    shutil.copy2(CODEC_CONFIG_SRC, CODEC_CONFIG_DST)\n",
        "    print(f'✅ Copied model_config.json → {CODEC_CONFIG_DST}')\n",
        "\n",
        "# ===== PATCH: ลบการตรวจสอบ flash_attn_2 ใน environment.py =====\n",
        "env_path = os.path.join(REPO_DIR, 'tts', 'training', 'environment.py')\n",
        "with open(env_path, 'r') as f:\n",
        "    env_code = f.read()\n",
        "\n",
        "env_code = env_code.replace(\n",
        "    'if not transformers_utils.is_flash_attn_2_available():',\n",
        "    'if False:  # [PATCHED] Disabled for T4 compatibility'\n",
        ")\n",
        "\n",
        "with open(env_path, 'w') as f:\n",
        "    f.write(env_code)\n",
        "\n",
        "print('✅ Patched environment.py: disabled flash_attn_2 check (T4 Safe!)')"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 🔬 ส่วนที่ 8: รัน Data Vectorization"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "VAL_SPLIT      = 0.05\n",
        "VEC_BATCH_SIZE  = 16\n",
        "VEC_NUM_WORKERS = 4\n",
        "VECTORIZED_DIR = os.path.join(KAGGLE_WORKING, 'dataset', 'vectorized_th')\n",
        "os.makedirs(VECTORIZED_DIR, exist_ok=True)\n",
        "\n",
        "os.chdir(REPO_DIR)\n",
        "import torch\n",
        "gpu_count = torch.cuda.device_count()\n",
        "nproc = gpu_count if gpu_count > 0 else 1\n",
        "\n",
        "cmd = [\n",
        "    'torchrun', f'--nproc_per_node={nproc}',\n",
        "    'tools/data/data_vectorizer.py',\n",
        "    f'--codec_model_path={XCODEC2_PATH}',\n",
        "    f'--batch_size={VEC_BATCH_SIZE}',\n",
        "    f'--num_workers={VEC_NUM_WORKERS}',\n",
        "    '--compile_model',\n",
        "    f'--dataset_path={OUTPUT_JSONL}',\n",
        "    f'--output_dir={VECTORIZED_DIR}',\n",
        "    f'--val_split={VAL_SPLIT}'\n",
        "]\n",
        "subprocess.run(cmd, check=True)\n",
        "print('\\n✅ Data Vectorization complete!')"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "### 📦 ส่วนที่ 9: รวมชิ้นส่วนข้อมูลให้เป็นก้อนเดียว (Merge Shards)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "os.chdir(REPO_DIR)\n",
        "subprocess.run([\n",
        "    sys.executable, 'tools/data/data_merger.py',\n",
        "    f'--dataset_path={VECTORIZED_DIR}',\n",
        "    '--remove_shards'\n",
        "], check=True)\n",
        "print('\\n✅ Shards merged!')"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "os.chdir(KAGGLE_WORKING)\n",
        "# 💾 เก็บไฟล์เสียงตัวอย่างไว้ 1 ไฟล์เพื่อใช้ทดสอบโคลนเสียงใน Notebook 2\n",
        "sample_wav_path = os.path.join(KAGGLE_WORKING, 'dataset', 'sample_prompt.wav')\n",
        "sample_txt_path = os.path.join(KAGGLE_WORKING, 'dataset', 'sample_transcript.txt')\n",
        "if os.path.exists(OUTPUT_JSONL):\n",
        "    with open(OUTPUT_JSONL, 'r', encoding='utf-8') as f:\n",
        "        first_line = f.readline().strip()\n",
        "        if first_line:\n",
        "            import json\n",
        "            import shutil\n",
        "            data = json.loads(first_line)\n",
        "            if os.path.exists(data['wav_path']):\n",
        "                shutil.copy2(data['wav_path'], sample_wav_path)\n",
        "                with open(sample_txt_path, 'w', encoding='utf-8') as txt_f:\n",
        "                    txt_f.write(data['transcript'])\n",
        "                print(f'🎤 เตรียมไฟล์ตัวอย่างสำหรับ Inference แล้ว: {sample_wav_path}')\n",
        "\n",
        "# ลบ prep/ ทั้งหมด (WAV, JSONL, Parquet) เพื่อประหยัดพื้นที่\n",
        "if os.path.exists(PREP_DIR):\n",
        "    shutil.rmtree(PREP_DIR)\n",
        "    print('🗑️ ลบ prep/ เรียบร้อย — ประหยัดพื้นที่สำหรับ Notebook 2')\n",
        "\n",
        "# สรุปสิ่งที่อยู่ใน dataset/\n",
        "dataset_dir = os.path.join(KAGGLE_WORKING, 'dataset')\n",
        "for root, dirs, files in os.walk(dataset_dir):\n",
        "    level = root.replace(dataset_dir, '').count(os.sep)\n",
        "    indent = ' ' * 2 * level\n",
        "    print(f'{indent}{os.path.basename(root)}/')\n",
        "    for f in files[:5]:\n",
        "        print(f'{indent}  {f}')\n",
        "    if len(files) > 5:\n",
        "        print(f'{indent}  ... และอีก {len(files)-5} ไฟล์')\n",
        "print('\\n✅ Output ใน dataset/ พร้อมสำหรับ Notebook 2 แล้ว!')"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "name": "python",
      "version": "3.10.12"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 4
}
